[TI-26] 특정 회차 선택 후 예매하기 버튼 클릭시 해당 회차의 모든 좌석정보들을 보내준다.
prgrms-be-devcourse/BEDV1_Interparkyu pull request #19
Opened 2021-10-30 16:38 UTC by HwiNyeonKim

* 선택된 공연의 회차에 (예매 가능한) 좌석 정보 조회 기능 구현 (모든 좌석 정보를 내려줌)

* 예매 가능한 좌석 정보만 보내주고, 그 외의 정보는 보내주지 않는 방법도 있음
  * 그러면 이 경우에는 API 반환 데이터에 좌석 끝번호 등의 데이터들을 덧붙여서 보내주어야 할 듯 하다.

2021-10-30 17:13 UTC, 0923kdh requested changes
seats 는 hall 도메인으로 포함하고, round_seats는 도메인 분리가 안된 상태로 알고 있습니다! seat를 seat 도메인으로, roundSeat는 roundSeat도메인으로 분리하신 이유가 있을까요? seat 도메인은 처음 논의했던대로 진행하는게 좋을 것 같고, roundSeat는 다시 협의해서 진행하면 좋을 것 같습니다~😀

2021-10-30 17:13 UTC, 0923kdh commented on src/main/java/org/programmers/interparkyu/Seat/SeatResponse.java
> +    public static SeatResponse from(Seat seat) {
@Builder 를 사용하면 좋을 것 같습니다~😊

2021-10-30 17:13 UTC, 0923kdh commented on src/main/java/org/programmers/interparkyu/roundSeat/RoundSeatRestController.java
> +public class RoundSeatRestController {
RoundSeatController 로 해도 의미 전달이 충분하지 않을까 생각합니다!😆

2021-10-30 17:35 UTC, HwiNyeonKim commented
딴문제 고민하다가 잠시 깜빡했습니다... 🙇‍♂️
다시돌려놓겠습니다! ƪ(ړײ)‎ƪ​​

2021-10-30 18:27 UTC, HwiNyeonKim commented on src/main/java/org/programmers/interparkyu/Seat/SeatResponse.java
> +    public static SeatResponse from(Seat seat) {
반영하였습니다!

2021-10-30 18:28 UTC, HwiNyeonKim commented on src/main/java/org/programmers/interparkyu/roundSeat/RoundSeatRestController.java
> +public class RoundSeatRestController {
넵. 생각해보니 이부분 다희님말씀이 맞는것같습니다. 반영하였습니다.

2021-10-30 18:38 UTC, HwiNyeonKim commented
원래 파일 하나하나 찾아서 되돌린 다음 커밋해야 하는데, 작업편의성을 위해서 reset 후 재커밋 하는식으로 이동된 파일 복원 및 피드백 반영을 했습니다. 좀 더 주의할게요! 😅

2021-10-31 09:34 UTC, sangmin7648 approved these changes
도메인 관련해서 다희님이 말씀하신 부분 뭔가하고 보려고 했는데 이미 수정된 부분인가요???

2021-10-31 09:34 UTC, sangmin7648 commented on src/main/java/org/programmers/interparkyu/hall/service/SeatService.java
> +            throw new NotFoundException(String.format("Wrong Seat ID is given %s", seatId));
추후에 NotFoundException을 상속해서 새로운 예외를 만드는 것도 좋을거 같습니다

2021-10-31 09:41 UTC, HwiNyeonKim commented
> 도메인 관련해서 다희님이 말씀하신 부분 뭔가하고 보려고 했는데 이미 수정된 부분인가요???

넵 다시 수정해서 재커밋 & 푸쉬된 상태입니다!

2021-10-31 09:44 UTC, HwiNyeonKim commented on src/main/java/org/programmers/interparkyu/hall/service/SeatService.java
> +            throw new NotFoundException(String.format("Wrong Seat ID is given %s", seatId));
테스팅 및 리팩터링의 하위이슈로 만들어서 한번에 처리하는 편이 좋을거 같은데, 어떻게 생각하시나요??

2021-10-31 09:45 UTC, 0923kdh approved these changes

2021-10-31 09:50 UTC, merged